apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: a2024-deployment
  labels:
    app: a2024
spec:
  replicas: 2
  selector:
    matchLabels:
      app: a2024
  template:
    metadata:
      labels:
        app: a2024
    spec:
      containers:
        - name: a2024
          image: elixirtech/elixir-ambience
          ports:
            - containerPort: 1740
          env:
            - name: externalhost
              value: "18.203.254.38"
            - name: externalport
              value: "80"
            - name: externalprotocol
              value: "HTTP:"
            - name: mongourl
              value: "mongodb://mongodb-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: a2024-service
spec:
  selector:
    app: a2024
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1740
      targetPort: 1740
      nodePort: 30001
