apiVersion: apps/v1
kind: Deployment
metadata:
  name: a2024-deployment
  labels:
    app: a2024
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a2024
  template:
    metadata:
      labels:
        app: a2024
    spec:
      containers:
        - name: a2024
          image: elixirtech/elixir-ambience
          ports:
            - containerPort: 1740
          env:
            - name: externalhost
#              value: "ec2-44-210-147-25.compute-1.amazonaws.com"
              value: "a6afb4bed3d364f02b4ca65048bb43cb-365105705.us-east-1.elb.amazonaws.com"
            - name: externalport
              value: "1740"
            - name: externalprotocol
              value: "http:"
            - name: mongourl
              value: "mongodb://mongodb-service:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: a2024-service
spec:
  selector:
    app: a2024
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 1740
      targetPort: 1740
      nodePort: 30001
