apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: a2024-ingress
#  namespace: kubernetes-dashboard
spec:
  ingressClassName: nginx
  rules:
  - host: ec2-44-198-61-198.compute-1.amazonaws.com
    http:
      paths:
      - path: /
        pathType: Exact  
        backend:
          service:
            name: a2024-service
            port: 
              number: 1741
