apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-deployment
  namespace: a2024
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: 'mongo:latest'
          name: elixir-mongo
          ports:
            - containerPort: 27017
          resources: {}
# Remove for fast testing
#          volumeMounts:
#            - mountPath: /data/db
#              name: elixirmongodbdata          
      restartPolicy: Always
#      volumes:
#        - name: elixirmongodbdata
#          persistentVolumeClaim:
#            claimName: elixirmongodbdata
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: a2024
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  creationTimestamp: null
#  labels:
#    io.kompose.service: elixirmongodbdata
#  name: elixirmongodbdata
#  namespace: a2024
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 100Mi
